name: Threat Feed Automation

on:
  schedule:
    - cron: '0 * * * *'  # Her 1 saatte bir
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Feed Engine
        run: python fetch_threats.py

      - name: Stage Only Text Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git reset -- .github/workflows/main.yml
          git add threat_ip.txt threat_domain.txt threat_url.txt threat_hash.txt

      - name: Commit and Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
